export const VOCABULARY = {
    'natureza': [
        { word: 'BALEA', clue: 'Mamífero acuático moi grande' },
        { word: 'CARBALLO', clue: 'Árbore típica de Galicia que dá landras' },
        { word: 'RULA', clue: 'Paxaro semellante á pomba, de canto suave' },
        { word: 'ORBALLO', clue: 'Chuvia moi fina, típica de Galicia' },
        { word: 'LÚA', clue: 'Satélite natural da Terra' },
        { word: 'MONTE', clue: 'Elevación natural do terreo' },
        { word: 'RIO', clue: 'Corrente natural de auga que vai ao mar' },
        { word: 'PRAIA', clue: 'Beira do mar formada por area' },
        { word: 'CASTIÑEIRO', clue: 'Árbore que dá castañas' },
        { word: 'SOL', clue: 'Estrela que nos dá luz e calor' },
        { word: 'RAIO', clue: 'Descarga eléctrica durante unha tormenta' },
        { word: 'TRONO', clue: 'Ruído forte despois dun raio' },
        { word: 'NEVE', clue: 'Auga conxelada que cae en folerpas' },
        { word: 'VENTO', clue: 'Aire en movemento' },
        { word: 'MAR', clue: 'Masa de auga salgada que cobre gran parte da Terra' },
        { word: 'PEDRA', clue: 'Materia mineral dura e sólida' },
        { word: 'FLOR', clue: 'Parte reprodutora das plantas, adoita ter cores' },
        { word: 'HERBA', clue: 'Planta pequena e verde que cobre o chan' },
        { word: 'PIÑEIRO', clue: 'Árbore de folla perenne que dá piñas' },
        { word: 'TOXO', clue: 'Arbusto con espiñas e flores amarelas' },
        { word: 'FUCHO', clue: 'Planta silvestre de flores amarelas e cheiro forte' },
        { word: 'SILVA', clue: 'Planta con espiñas que dá amoras' },
        { word: 'AMORA', clue: 'Froito silvestre de cor negra ou vermella' },
        { word: 'LANDRA', clue: 'Froito do carballo' },
        { word: 'COGOMELO', clue: 'Fungo con forma de sombreiro' },
        { word: 'VAL', clue: 'Terreo baixo entre montañas' },
        { word: 'OUTEIRO', clue: 'Pequena elevación de terreo illada' },
        { word: 'FRAGA', clue: 'Bosque espeso con moitas especies de árbores' },
        { word: 'REGO', clue: 'Canle pequena por onde vai a auga' },
        { word: 'FONTE', clue: 'Lugar onde brota auga da terra' },
        { word: 'POZA', clue: 'Pequena cantidade de auga estancada' },
        { word: 'LAGO', clue: 'Masa grande de auga doce ou salgada rodeada de terra' },
        { word: 'NOITE', clue: 'Parte do día sen luz solar' },
        { word: 'MENCER', clue: 'Comezo do día, cando sae o sol' },
        { word: 'LUSCOFUSCO', clue: 'Momento entre o día e a noite' },
        { word: 'ESTRELA', clue: 'Corpo celeste que brilla con luz propia' },
        { word: 'NUBE', clue: 'Masa de vapor de auga no ceo' },
        { word: 'ARCO DA VELLA', clue: 'Arco de cores que sae cando chove e fai sol' },
        { word: 'BOSQUE', clue: 'Terreo poboado de árbores' },
        { word: 'CAMIÑO', clue: 'Vía de terra para ir dun sitio a outro' },
        { word: 'TERRA', clue: 'O planeta onde vivimos ou o chan que pisamos' },
        { word: 'AUGA', clue: 'Líquido esencial para a vida' },
        { word: 'LUME', clue: 'Calor e luz producidos pola combustión' },
        { word: 'FUME', clue: 'Gas que sae do lume' },
        { word: 'CINZA', clue: 'O que queda despois de que algo se queima' }
    ],
    'animais': [
        { word: 'LOBO', clue: 'Cánido salvaxe que vive nos montes' },
        { word: 'RAPOSO', clue: 'Animal astuto de cola longa e peluxe avermellada' },
        { word: 'XABARIN', clue: 'Porco bravo que vive no monte' },
        { word: 'RA', clue: 'Anfibio que croa e salta' },
        { word: 'CAN', clue: 'O mellor amigo do home' },
        { word: 'GATO', clue: 'Felino doméstico que caza ratos' },
        { word: 'VACA', clue: 'Animal que dá leite e muxe' },
        { word: 'CABALO', clue: 'Animal grande usado para montar' },
        { word: 'OVELLA', clue: 'Animal que dá la' },
        { word: 'CABRA', clue: 'Animal que gabea e ten cornos' },
        { word: 'PORCO', clue: 'Animal de granxa do que se aproveita todo' },
        { word: 'GALIÑA', clue: 'Ave de curral que pon ovos' },
        { word: 'GALO', clue: 'O macho da galiña, canta ao amencer' },
        { word: 'COELLO', clue: 'Animal de orellas longas que come cenorias' },
        { word: 'RATO', clue: 'Roedor pequeno que teme aos gatos' },
        { word: 'OSO', clue: 'Animal grande e peludo que hiberna' },
        { word: 'CERVO', clue: 'Animal do bosque con cornos ramificados' },
        { word: 'CORZO', clue: 'Pequeno cervo dos bosques galegos' },
        { word: 'AGUIA', clue: 'Ave rapaz de gran vista' },
        { word: 'CURUXA', clue: 'Ave nocturna de ollos grandes' },
        { word: 'MOCHO', clue: 'Ave rapaz nocturna parecida á curuxa' },
        { word: 'RULA', clue: 'Ave parecida á pomba' },
        { word: 'POMBA', clue: 'Ave símbolo da paz' },
        { word: 'GAIVOTA', clue: 'Ave branca que vive preto do mar' },
        { word: 'PEIXE', clue: 'Animal que vive baixo a auga e ten aletas' },
        { word: 'POLBO', clue: 'Animal mariño con oito tentáculos' },
        { word: 'CHOCO', clue: 'Cefalópodo parecido á lura' },
        { word: 'MEXILLON', clue: 'Molusco de cuncha negra típico das rías' },
        { word: 'AMEIXA', clue: 'Molusco bivalvo moi prezado' },
        { word: 'PERCEBE', clue: 'Crustáceo que medra nas rochas batidas polo mar' },
        { word: 'CENTOLA', clue: 'Crustáceo grande con patas longas' },
        { word: 'SARDINA', clue: 'Peixe pequeno e azul, típico do San Xoán' },
        { word: 'TROITA', clue: 'Peixe de río con pintas' },
        { word: 'SALMON', clue: 'Peixe que remonta os ríos para desovar' },
        { word: 'SAPO', clue: 'Anfibio de pel rugosa' },
        { word: 'COBRA', clue: 'Réptil longo e sen patas' },
        { word: 'LAGARTO', clue: 'Réptil de cola longa que toma o sol' },
        { word: 'MOSCA', clue: 'Insecto voadaor moi molesto' },
        { word: 'ABELLA', clue: 'Insecto que produce mel' },
        { word: 'AVISPA', clue: 'Insecto que pica e ten raias amarelas e negras' },
        { word: 'FORMIGA', clue: 'Insecto traballador que vive en colonias' },
        { word: 'CARACOL', clue: 'Animal que leva a casa ás costas' },
        { word: 'BOLBORETA', clue: 'Insecto de ás coloridas que nace dunha eiruga' }
    ],
    'cociña': [
        { word: 'TENEDOR', clue: 'Utensilio con puga para picar a comida' },
        { word: 'CUNCAL', clue: 'Recipiente para beber viño ou caldo' },
        { word: 'FOGON', clue: 'Lugar onde se fai o lume para cociñar' },
        { word: 'SARTEN', clue: 'Utensilio para fritir alimentos' },
        { word: 'POTAS', clue: 'Recipientes fondos para cociñar' },
        { word: 'OLLA', clue: 'Recipiente grande para cociñar' },
        { word: 'FORNO', clue: 'Electrodoméstico para asar alimentos' },
        { word: 'VERDURA', clue: 'Hortaliza comestible' },
        { word: 'FARIÑA', clue: 'Po obtido de moer cereais' },
        { word: 'SAL', clue: 'Substancia branca para dar sabor salgado' },
        { word: 'ACEITE', clue: 'Graxa líquida vexetal' },
        { word: 'PAN', clue: 'Alimento básico feito de fariña e auga' },
        { word: 'QUEIXO', clue: 'Alimento sólido feito co leite' },
        { word: 'MEL', clue: 'Substancia doce producida polas abellas' },
        { word: 'CALDO', clue: 'Prato típico galego con verdura e patacas' },
        { word: 'EMPANADA', clue: 'Masa de pan rechea de carne ou peixe' },
        { word: 'PULPO', clue: 'Prato tradicional de feira' },
        { word: 'LACÓN', clue: 'Pata dianteira do porco curada' },
        { word: 'GRELOS', clue: 'Follas do nabo, típicas do lacón con grelos' },
        { word: 'PATACA', clue: 'Tubérculo moi usado na cociña galega' },
        { word: 'CEBOLA', clue: 'Hortaliza que fai chorar ao picala' },
        { word: 'ALLO', clue: 'Dente de sabor forte usado para condimentar' },
        { word: 'PEMENTO', clue: 'Hortaliza verde ou vermella, algúns pican' },
        { word: 'TOMATE', clue: 'Froito vermello usado en ensaladas e salsas' },
        { word: 'LEITUGA', clue: 'Follas verdes para facer ensalada' },
        { word: 'OVO', clue: 'Produto da galiña protexido por unha casca' },
        { word: 'LEITE', clue: 'Líquido branco producido polas vacas' },
        { word: 'IAUR', clue: 'Leite fermentado' },
        { word: 'MANTEIGA', clue: 'Graxa do leite para untar ou cociñar' },
        { word: 'AZUCAR', clue: 'Substancia para endulzar' },
        { word: 'CAFÉ', clue: 'Bebida escura e estimulante' },
        { word: 'VIÑO', clue: 'Bebida alcohólica feita de uvas' },
        { word: 'AUGA', clue: 'Líquido esencial para beber' },
        { word: 'ZUME', clue: 'Líquido que se saca das froitas' },
        { word: 'MAZÁ', clue: 'Froita redonda que pode ser vermella, verde ou amarela' },
        { word: 'PERA', clue: 'Froita suculenta con forma de lámpada' },
        { word: 'NARANXA', clue: 'Cítrico de cor laranxa rico en vitamina C' },
        { word: 'LIMON', clue: 'Cítrico amarelo e moi ácido' },
        { word: 'PLATANO', clue: 'Froita amarela e curva' },
        { word: 'MESA', clue: 'Mobele onde se come' },
        { word: 'CADEIRA', clue: 'Asento para sentar á mesa' },
        { word: 'SERVILETA', clue: 'Pano ou papel para limparse a boca' },
        { word: 'CUCHILO', clue: 'Utensilio para cortar' },
        { word: 'CULLER', clue: 'Utensilio para tomar sopa' },
        { word: 'PRATO', clue: 'Onde se serve a comida' }
    ],
    'corpo': [
        { word: 'CABEZA', clue: 'Parte superior do corpo' },
        { word: 'MAN', clue: 'Parte final do brazo con dedos' },
        { word: 'PE', clue: 'Parte inferior da perna para andar' },
        { word: 'OLLO', clue: 'Órgano da vista' },
        { word: 'NARIZ', clue: 'Órgano do olfacto' },
        { word: 'BOCA', clue: 'Abertura para comer e falar' },
        { word: 'ORELLA', clue: 'Órgano do oído' },
        { word: 'PELO', clue: 'Fío que nace na pel' },
        { word: 'DEDO', clue: 'Cada unha das partes en que remata a man' },
        { word: 'UNLLA', clue: 'Parte dura que cobre a punta dos dedos' },
        { word: 'CORAZON', clue: 'Órgano que bombea o sangue' },
        { word: 'SANGUE', clue: 'Líquido vermello que circula polo corpo' },
        { word: 'OSOS', clue: 'Partes duras que forman o esqueleto' },
        { word: 'DENTES', clue: 'Pezas duras na boca para mastigar' },
        { word: 'LINGUA', clue: 'Órgano na boca para o gusto e a fala' },
        { word: 'BRAZO', clue: 'Extremidade superior dende o ombreiro á man' },
        { word: 'PERNA', clue: 'Extremidade inferior para camiñar' },
        { word: 'XEONLLO', clue: 'Articulación central da perna' },
        { word: 'COBADO', clue: 'Articulación central do brazo' },
        { word: 'OMBREIRO', clue: 'Parte onde se une o brazo ao tronco' },
        { word: 'PESCOZO', clue: 'Parte que une a cabeza ao tronco' },
        { word: 'TRONCO', clue: 'Parte central do corpo' },
        { word: 'PEITO', clue: 'Parte dianteira superior do tronco' },
        { word: 'BARRIGA', clue: 'Parte dianteira inferior do tronco' },
        { word: 'COSTAS', clue: 'Parte posterior do tronco' },
        { word: 'CARA', clue: 'Parte dianteira da cabeza' },
        { word: 'TESTA', clue: 'Parte superior da cara' },
        { word: 'BIVENTRE', clue: 'Barriga ou ventre' },
        { word: 'RIL', clue: 'Órgano que filtra o sangue' },
        { word: 'PULMON', clue: 'Órgano da respiración' },
        { word: 'ESTOMAGO', clue: 'Órgano onde se dixiren os alimentos' },
        { word: 'FIGADO', clue: 'Órgano grande que limpa o sangue' },
        { word: 'INTESTINO', clue: 'Tubo longo onde se absorben os alimentos' },
        { word: 'VEAS', clue: 'Condutos polos que volve o sangue ao corazón' },
        { word: 'ARTERIAS', clue: 'Condutos que levan o sangue dende o corazón' },
        { word: 'PEL', clue: 'Capa que cobre todo o corpo' },
        { word: 'CEREBRO', clue: 'Órgano que controla o corpo e o pensamento' },
        { word: 'LABIO', clue: 'Bordo carnoso da boca' },
        { word: 'DENTE', clue: 'Peza branca dura da boca' },
        { word: 'MOA', clue: 'Dente posterior para moer' },
        { word: 'QUEIXO', clue: 'Parte inferior da cara' },
        { word: 'CELLAS', clue: 'Pelo enriba dos ollos' },
        { word: 'PESTANAS', clue: 'Peliños no bordo dos párpados' }
    ],
    'casa': [
        { word: 'PORTA', clue: 'Abertura para entrar e saír' },
        { word: 'XANELA', clue: 'Abertura na parede para dar luz' },
        { word: 'TEITO', clue: 'Parte superior que cobre unha estancia' },
        { word: 'PAREDE', clue: 'Muro que pecha un espazo' },
        { word: 'CHAN', clue: 'Superficie pola que se anda' },
        { word: 'COCIÑA', clue: 'Lugar onde se prepara a comida' },
        { word: 'BAÑO', clue: 'Lugar para o aseo persoal' },
        { word: 'SALA', clue: 'Cuarto para estar e recibir visitas' },
        { word: 'QUARTO', clue: 'Estancia para durmir' },
        { word: 'CAMA', clue: 'Mobele para durmir' },
        { word: 'MESA', clue: 'Mobele para comer ou traballar' },
        { word: 'CADEIRA', clue: 'Asento con respaldo' },
        { word: 'SOFA', clue: 'Asento cómodo para varias persoas' },
        { word: 'LAMPADA', clue: 'Obxecto que dá luz artificial' },
        { word: 'CHAVE', clue: 'Instrumento para abrir a porta' },
        { word: 'ESCALEIRA', clue: 'Serie de chanzo para subir e baixar' },
        { word: 'TELLADO', clue: 'Cuberta exterior superior da casa' },
        { word: 'CHAMINEA', clue: 'Conduto para que saia o fume' },
        { word: 'XARDIN', clue: 'Terreo con plantas arredor da casa' },
        { word: 'GARAXE', clue: 'Lugar para gardar o coche' },
        { word: 'PASILLO', clue: 'Corredor que comunica as habitacións' },
        { word: 'DESVAN', clue: 'Parte máis alta da casa, baixo o tellado' },
        { word: 'SOTO', clue: 'Parte da casa baixo terra' },
        { word: 'ARMARIO', clue: 'Mobele para gardar roupa ou cousas' },
        { word: 'CAIXON', clue: 'Caixa corredía nun moble' },
        { word: 'ESTANTE', clue: 'Táboa horizontal para poñer cousas' },
        { word: 'ALFOMBRA', clue: 'Tecido groso para cubrir o chan' },
        { word: 'CORTINA', clue: 'Tea para cubrir as xanelas' },
        { word: 'ESPELLO', clue: 'Vidro que reflicte a imaxe' },
        { word: 'CADRO', clue: 'Pintura ou foto enmarcada na parede' },
        { word: 'RELOXO', clue: 'Aparato para medir o tempo' },
        { word: 'GRIFA', clue: 'Chave para abrir ou pechar a auga' },
        { word: 'LAVABO', clue: 'Pia para lavar as mans e a cara' },
        { word: 'DUCHA', clue: 'Instalación para bañarse de pé' },
        { word: 'BATEIRA', clue: 'Recipiente grande para bañarse' },
        { word: 'TOALLA', clue: 'Pano para secarse' },
        { word: 'SAVAS', clue: 'Roupa de cama' },
        { word: 'MANTA', clue: 'Roupa de abrigo para a cama' },
        { word: 'ALMOFADA', clue: 'Coxín para apoiar a cabeza na cama' },
        { word: 'COLCHON', clue: 'Parte branda da cama onde nos deitamos' },
        { word: 'VASOIRA', clue: 'Utensilio para varrer o chan' },
        { word: 'FREGONA', clue: 'Utensilio para lavar o chan' }
    ],
    'escola': [
        { word: 'LIBRO', clue: 'Conxunto de follas de papel escritas e encadernadas' },
        { word: 'LIBRERIA', clue: 'Mobele para gardar libros' },
        { word: 'CADERNO', clue: 'Libro en branco para escribir' },
        { word: 'LAPIS', clue: 'Utensilio de madeira e grafito para escribir' },
        { word: 'BOLIGRAFO', clue: 'Utensilio con tinta para escribir' },
        { word: 'GOMA', clue: 'Obxecto para borrar o escrito con lapis' },
        { word: 'AFIALAPIS', clue: 'Utensilio para afiar os lapis' },
        { word: 'ESTOXO', clue: 'Bolsa ou caixa para gardar lapis e bolígrafos' },
        { word: 'MOCHILA', clue: 'Bolsa que se leva ás costas' },
        { word: 'PIZARRA', clue: 'Superficie para escribir con xiz ou rotulador' },
        { word: 'XIZ', clue: 'Barriña branca ou de cor para escribir na lousa' },
        { word: 'BORRADOR', clue: 'Utensilio para limpar a pizarra' },
        { word: 'MESTRA', clue: 'Persoa que ensina na escola' },
        { word: 'ALUMNO', clue: 'Persoa que aprende na escola' },
        { word: 'CLASE', clue: 'Aula ou grupo de alumnos' },
        { word: 'RECREO', clue: 'Tempo de descanso entre clases' },
        { word: 'EXAME', clue: 'Proba para demostrar o que se sabe' },
        { word: 'NOTA', clue: 'Cualificación dun exame ou traballo' },
        { word: 'DEBERES', clue: 'Traballo para facer na casa' },
        { word: 'LECCION', clue: 'O que se ensina nunha clase' },
        { word: 'MAPA', clue: 'Debuxo que representa un territorio' },
        { word: 'GLOBO', clue: 'Esfera que representa a Terra' },
        { word: 'ORDENADOR', clue: 'Máquina electrónica para procesar información' },
        { word: 'PANTALLA', clue: 'Parte do ordenador onde se ven as imaxes' },
        { word: 'RATO', clue: 'Dispositivo para mover o cursor no ordenador' },
        { word: 'TECLADO', clue: 'Conxunto de teclas para escribir no ordenador' },
        { word: 'MESA', clue: 'Mobele onde estuda o alumno' },
        { word: 'CADEIRA', clue: 'Asento do alumno' },
        { word: 'PAPEL', clue: 'Folla fina para escribir ou debuxar' },
        { word: 'TESOIRAS', clue: 'Utensilio para cortar papel' },
        { word: 'PEGAMENTO', clue: 'Substancia para pegar cousas' },
        { word: 'REGRA', clue: 'Utensilio recto para medir e facer liñas' },
        { word: 'COMPAS', clue: 'Utensilio para facer círculos' },
        { word: 'DICIONARIO', clue: 'Libro que explica o significado das palabras' },
        { word: 'BIBLIOTECA', clue: 'Lugar onde se gardan e len libros' },
        { word: 'XIMNASIO', clue: 'Lugar para facer deporte na escola' },
        { word: 'COMEDOR', clue: 'Lugar onde comen os alumnos' },
        { word: 'PATIO', clue: 'Espazo aberto para xogar no recreo' }
    ],
    'roupa': [
        { word: 'CAMISA', clue: 'Roupa con botóns e mangas para o tronco' },
        { word: 'CAMISETA', clue: 'Roupa de punto sen botóns' },
        { word: 'PANTALON', clue: 'Roupa que cobre as pernas' },
        { word: 'SAIA', clue: 'Roupa que cae dende a cintura sen dividir as pernas' },
        { word: 'VESTIDO', clue: 'Roupa dunha soa peza que cobre o corpo e pernas' },
        { word: 'XERSEI', clue: 'Roupa de la ou punto para o frío' },
        { word: 'CHAQUETA', clue: 'Roupa de abrigo aberta por diante' },
        { word: 'ABRIGO', clue: 'Roupa longa para protexerse do frío' },
        { word: 'BUFANDA', clue: 'Pano longo para abrigar o pescozo' },
        { word: 'LUVAS', clue: 'Roupa para cubrir as mans' },
        { word: 'GORRO', clue: 'Roupa para cubrir a cabeza' },
        { word: 'SOMBREIRO', clue: 'Gorro con aba arredor' },
        { word: 'CALCETINS', clue: 'Roupa que cobre os pés' },
        { word: 'ZAPATOS', clue: 'Calzado que protexe o pé' },
        { word: 'BOTAS', clue: 'Calzado que cobre o pé e parte da perna' },
        { word: 'DEPORTIVAS', clue: 'Zapatos para facer deporte' },
        { word: 'SANDALIAS', clue: 'Calzado aberto para o verán' },
        { word: 'CINTO', clue: 'Tira para suxeitar o pantalón' },
        { word: 'GRAVATA', clue: 'Tira de tea que se anuda ao pescozo' },
        { word: 'PAXARITA', clue: 'Lazo que se leva no pescozo' },
        { word: 'CHANDAL', clue: 'Roupa cómoda para facer deporte' },
        { word: 'PIXAMA', clue: 'Roupa para durmir' },
        { word: 'BATA', clue: 'Roupa para estar pola casa enriba do pixama' },
        { word: 'BAÑADOR', clue: 'Roupa para bañarse na praia ou piscina' },
        { word: 'IMPERMEABLE', clue: 'Roupa para protexerse da chuvia' },
        { word: 'PARAUGAS', clue: 'Obxecto para non mollarse cando chove' },
        { word: 'BOLSO', clue: 'Saco pequeno para levar cousas persoais' },
        { word: 'CARRTEIRA', clue: 'Obxecto para levar o diñeiro e tarxetas' },
        { word: 'XOIA', clue: 'Obxecto de adorno persoal de valor' },
        { word: 'ANEL', clue: 'Aro que se pon no dedo' },
        { word: 'COLAR', clue: 'Adorno que se leva ao pescozo' },
        { word: 'PENDENTE', clue: 'Adorno que se pon na orella' },
        { word: 'RELOXO', clue: 'Aparato de pulso para ver a hora' },
        { word: 'GAFAS', clue: 'Lentes para ver mellor ou protexerse do sol' },
        { word: 'BOTON', clue: 'Peca pequena para abrochar a roupa' },
        { word: 'CREMALLERA', clue: 'Peche dentado para a roupa' },
        { word: 'BOLSILLO', clue: 'Saquiño cosido na roupa' },
        { word: 'FIO', clue: 'Cordoniciño usado para coser' },
        { word: 'AGULLA', clue: 'Barriña de metal para coser' }
    ]
};
